--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-11 12:05:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 32794)
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    id integer NOT NULL,
    description character varying(255),
    enddate timestamp(6) with time zone NOT NULL,
    startdate timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT tasks_status_check CHECK (((status)::text = ANY ((ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 32793)
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4790 (class 0 OID 32794)
-- Dependencies: 218
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks (id, description, enddate, startdate, status, title, type) FROM stdin;
1	Lire la sainte bible, Lire le journal, lire un roman	2025-04-15 16:00:00+00	2025-04-01 12:30:00+00	TODO	projet de lecture	PERSONNEL
3	Compile les données financière de mars, inclure l'analyse des tendances	2025-04-15 16:00:00+00	2025-04-02 12:30:00+00	IN_PROGRESS	Rapport mensuel	Work
5	Prioriser les tâches, fixer les objectifs journaliers	2025-04-15 16:00:00+00	2025-04-01 12:30:00+00	TODO	Planifier la semaine	WORK
4	Prioriser les tâches, fixer les objectifs journaliers	2025-04-15 16:00:00+00	2025-04-01 12:30:00+00	DONE	Planifier la semaine	WORK
7	inventory of the articles	2025-04-09 13:25:40.688+00	2025-04-09 13:25:40.688+00	TODO	monthly sale	PERSONNAL
\.


--
-- TOC entry 4796 (class 0 OID 0)
-- Dependencies: 217
-- Name: tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_id_seq', 7, true);


--
-- TOC entry 4643 (class 2606 OID 32801)
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


-- Completed on 2025-04-11 12:05:56

--
-- PostgreSQL database dump complete
--

